### ISSUE TITLE
Replace search strategy to Algolia DocSearch

### ISSUE THREAD

**Issue by bluwy** [rainmeter/rainmeter-docs#13]
I recently found out about [Algolia DocSearch](https://community.algolia.com/docsearch/) which provides free search indexing for documentations. It would be nice to have it replace the current one which uses Google search.

Overall, it would provide better UX when navigating around the docs since the search now stay on the same page. The service is free anyways and seems intuitive :)

Looking forward for thoughts on this.

**Comment by bluwy** [comment]
Any news on this? I'll be glad to help out setting this up, but it needs me to have write permission and to submit an email.

I don't mind closing this issue if it's not worth implementing.

**Comment by brianferguson** [comment]
Seems like a nice service, especially the UX, and we may look into this at some point, but I think we will stay with Google search for now.

Google search crawls our docs site several times a day, instead of just once. Sometimes we make lots of changes in a day. Not a huge deal for a project ours, but it can make a difference for our international users that might end up getting a cached version from the CDN (not sure what DocSearch uses). Although the google search goes to their site, their content is spread through their CDN system very quickly. It's still the fastest, most up to date option at the expense of a neat UX that DocSearch does right on the site through javascript.

-Brian
